language: python
python:
  - '3.5'
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - wget https://yarnpkg.com/latest.tar.gz && tar -xf latest.tar.gz
  - export PATH=$PATH:$PWD/dist/bin
  - pip install tox
script: tox
notifications:
  slack:
    secure: d/EydhRyGnY6n3qWpF7HGfuKcOgmNTZH0xHd/LqVSU3pnsCPtyguaWDhpyFhJR/oB8eY++c60A3U5ysjo7B5YszoeUPqBsaJzdJzf1r3Hg3GGyn+l8q2IkupQMrUKnEB0DCim9fC11AmPQO4oWNmVz/uztzQ0Qr4XlbXVPPTOD0vabzUNQplXk2dtQ3aJeYk64RCqFylkJE//EYPIN1jE86DciyIPsFL+NCcxNe+l022M4NI9TjM0nkYBHrmFf2gdskZ0av8RH4HPuQ2CqRaVZm7ZGWriF2ZRb5YE+Q+jSHMiaHWZDLp8wGxf2uJilqdic1Wve+v3a1e4E0Il0PIKegGyzHrOadbEk6hAf6v+D5U7e0MbHi8S+dBSsRc94gw26wzef9o7iWWx3WxqpSJ1n1gYo/MnA8/Hnw2X/k6cDnWOA1ie2eH9jXhyvwgNH1qVzdtVGQbXe6V88/sTCLrB50K6uuzTzZGaggNqantTLae1CkPbKbsDuCPQspI386aemxlEsGjzjdJqBsLnYR1QIsYjHt0KiiSxOrGhXkusACCBXJPvGlJcBlOAtSK+tAd1H4rjDTuN8772NOm5RNFAdvk8fbnh3w3m0KKBqfU4O2nD6URV3V/URZM9LcButhHIedLoIIdGRmlqtcQtZqOb8xqJHPexIArIOwvo2v4XEw=
    on_success: change
    on_failure: change
cache: yarn
