# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.CharField(choices=[('FB', 'Facebook'), ('TWT', 'Twitter'), ('WEB', 'Website'), ('TEL', 'Telephone number'), ('EM', 'Email')], max_length=3)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(max_length=80)),
                ('google_id', models.CharField(max_length=20)),
                ('bioguide_id', models.CharField(db_index=True, max_length=20)),
                ('wikipedia_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('chamber', models.CharField(choices=[('SEN', 'Senate'), ('HOR', 'House of Representatives')], max_length=3)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent'), ('G', 'Green'), ('L', 'Libertarian')], max_length=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.District')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.Representative')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.State'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.Representative'),
        ),
    ]
