# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0002_auto_20161202_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.Representative')),
            ],
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['state__name', 'number']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-end']},
        ),
        migrations.AddField(
            model_name='activeterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislature.Term'),
        ),
    ]
