# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0003_auto_20161207_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='legislature.Representative'),
        ),
    ]
