# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislature', '0004_auto_20161214_0237'),
        ('questing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight_id', models.CharField(max_length=63)),
                ('official_title', models.TextField()),
                ('popular_title', models.CharField(max_length=127)),
                ('summary', models.TextField()),
                ('url', models.CharField(help_text='Permalink with more info', max_length=127)),
                ('chamber', models.CharField(choices=[('S', 'Senate'), ('H', 'House')], max_length=3)),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.Representative')),
                ('topics', models.ManyToManyField(to='questing.Topic')),
            ],
        ),
    ]
