# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='chamber',
            field=models.CharField(choices=[('S', 'Senate'), ('H', 'House')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='official_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='popular_title',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='bill',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sunlight_id',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='bill',
            name='url',
            field=models.CharField(default='', help_text='Permalink with more info', max_length=127),
        ),
    ]
